---
# ------------------------------------------------------------------
#         setup bash profile for  OS users Oracle 
# ------------------------------------------------------------------
- name: bash_profile for oracle user
  blockinfile:
    path: /home/oracle/.bash_profile
    insertafter: '#### for oracle #####'
    state: present
    block: |
      export PATH=$PATH:$HOME/bin
      export PATH=/usr/bin:$PATH
      export LD_LIBRARY_PATH=/usr/lib:/lib
      export NLS_LANG=AMERICAN_AMERICA.UTF8
      export NLS_DATE_FORMAT='DD-MM-YYYY:HH24:MI:SS'
