---
# ==============================================================================
# Oracle 19C database installation
# ==============================================================================

- name: Database pre software install message
  debug:
    msg:
      - 'Oracle Database Software 19c Installation started for Single Instance at {{ansible_date_time.iso8601}}:'

- name: Preparation tasks for hosting Oracle database
  block:
    - import_tasks: Step0_pre-check.yml
    # - import_tasks: Step1_facts_to_file.yml # Enable this if not running OS Pre Role
    # - import_tasks: Step2_SUDO.yml # Enable this if not running OS Pre Role
    - import_tasks: Step3_OS_Prereq.yml
    - import_tasks: Step4_Create_Directory.yml
    - import_tasks: Step5_Unarchive.yml
    - import_tasks: Step6_Responsefile.yml
    - import_tasks: Step7_installbinary.yml
    - import_tasks: Step8_Execute_root.yml
    - import_tasks: Step9_SQLPLUS.yml


- name: display post install message
  debug:
    msg:
      - 'This Steps completed below task for Single Instance at {{ansible_date_time.iso8601}}:'
      - '- Install Single Instance Oracle Database Software'
      - 'Next Steps left to do:'
      - '- Create SI empty Container Database on server ora-x1'
      - '- Create SI Pluggable Database on server ora-x1'
      - '- Deinstall Single Instance Oracle Database Software'
      - '- END OF ALL: git clone of OracleDBAwithAnsible repository will be shared'


 
# - name: Print ORACLE HOME list from default var files
#   ansible.builtin.debug:
#     msg:
#       - "ORACLE HOME -> {{ oracle_home }}"
#       - "ORACLE BASE -> {{ oracle_base }}"
#       - "ORACLE BINARY -> {{ oracle_gold_image }}"