---
# ------------------------------------------------------------------------------
# Setup necessary kernel parameters and reload using sysctl -p
# ------------------------------------------------------------------------------
- name: setup necessary kernel parameters 
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items: "{{ kernel_params }}"
