---
# ---------------------------------------
# Install Oracle required packages
# ---------------------------------------


- include_vars: rhel8_environment_vars.yml
  name: packages_list
  when: ansible_distribution_major_version == "8"

- include_vars: rhel9_environment_vars.yml
  name: packages
  when: ansible_distribution_major_version == "9"

- name: Install required libraries
  # yum: name={{ ansible_facts.packages_list }} state=present
  debug:
    var: "{{ ansible_facts[packages_list][rpm] }}"
  # with_items: "{{ ansible_facts[packages_list] }}"

