---
# ----------------------------------------------------
#        Create required directories
# ----------------------------------------------------
- name: Check if Directory already exists 
  ansible.builtin.stat:
    path: "{{ oracle_base }}"
  register: fs_stats


- name: create required directories
  file:
    path="{{ item }}"
    state=directory
    owner="{{ oracle_user }}"
    group="{{ oracle_install_group }}"
    mode=0750
  with_items:
    - "{{ oracle_base }}"
    - "{{ oracle_home }}"
  tags:
    - dbcreate_crdirs
  # when: not fs_stats.stat.exists



#Disabled below
# - name: Check if Directory already exists 
#   ansible.builtin.stat:
#     path: "{{ oracle_base }}"
#   register: fs_stats

# - name: Rename Directory if already exists
#   command: mv "{{ oracle_base }}" "{{ oracle_base }}_{{ ansible_date_time.date }}"
#   # debug:
#   #   msg: Directory already exists
#   when: fs_stats.stat.exists == 'true'


# - name: Check if Directory already exists 
#   ansible.builtin.stat:
#     path: "{{ oracle_home }}"
#   register: fs_stats

# - name: Rename Directory if already exists
#   command: mv "{{ oracle_home }}" "{{ oracle_home }}_{{ ansible_date_time.date }}"
#   # debug:
#   #   msg: Directory already exists
#   when: fs_stats.stat.exists == 'true'