---
# ------------------------------------------------------------------
#         Pre-req to perform the steps
# ------------------------------------------------------------------

- name: Check if Directory already exists 
  ansible.builtin.stat:
    path: "{{ oracle_home }}"
  register: fs_stats

- name: ORACLE_HOME Directry already exists
  ansible.builtin.fail:
    msg: "{{ oracle_home }} directroy already exists"
  when: fs_stats.stat.exists

- name: Check if oracle user is exists with group id
  ansible.builtin.user:
    name: "{{ oracle_user }}"
    uid: "{{ oracle_user_uid }}"
    group: "{{ oracle_install_group }}"
  check_mode: true
  register: user_stats
   
# - name: Oracle OS user status
#   debug:
#     var: user_stats

- name: Oracle OS user status
  ansible.builtin.fail:
    msg: "User {{ oracle_user }}  exists with uid {{ oracle_user_uid }}"
  when:  (user_stats.uid != 500 )


- name: Check if oradba group  is exists with group id
  ansible.builtin.group:
    name: "{{ oracle_install_group }}"
    gid: "{{ oracle_install_group_uid }}"

  check_mode: true
  register: group_stats
   
# - name: oradba group status
#   debug:
#     var: group_stats

- name: oradba group status
  ansible.builtin.fail:
    msg: "Group {{ group_stats }}  exists with gid {{ oracle_install_group_uid }}"
  when:  (group_stats.gid != 503 )
