---
- name: create required directories
  file:
    path="{{ item }}"
    state=directory
    owner="{{ oracle_user }}"
    group="{{ oracle_install_group }}"
    mode=0775
  with_items:
    # - "{{ oracle_inventory }}" #ENABLE if running only DB install ROLE
    # - "{{ oracle_base }}" #ENABLE if running only DB install ROLE
    - "{{ stage_dir }}"
    # - "{{ oracle_home }}" #ENABLE if running only DB install ROLE
  tags:
   - db19c_createinventory