---
#Write the facts to local file
#Contiues to proceed even if there is failure
- name: save all facts to host specific file
  copy:
    # content: "{{ ansible_delegated_vars[inventory_hostname].vars | to_nice_json }}"
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "{{ playbook_dir }}/facts/{{ ansible_fqdn }}"
  delegate_to: localhost
  ignore_errors: true