---

#
# RUN SQL Scripts
#
- name: Post DB | execute DB scripts
  shell: export ORACLE_HOME={{ oracle_home }}; export ORACLE_SID={{ db_name }}; export PATH=$PATH:$ORACLE_HOME/bin; echo "@{{ item }};" | {{ oracle_home }}/bin/sqlplus / as sysdba
  register: sqlplus_dbvalidate
  ignore_errors: True
  with_items:
    - /oradba/scripts/Gilead_standards_creation.sql
    - "{{ stage_dir }}/update_unique_name.sql"
    - "{{ stage_dir }}/blockchange_tracking.sql"
    - "{{ stage_dir }}/enable_dbarchlogs.sql"
    - "{{ stage_dir }}/db_shutdown.sql"


- name: display DB validation output message
  debug:
    msg: "{{item.stdout|trim}}"
  # debug: msg="{{ sqlplus_dbvalidate |trim}}"
  with_items: "{{ sqlplus_dbvalidate.results }}"
  # with_items: "{{ sqlplus_dbvalidate.results|map(attribute='stdout')|list }}"

