---
# ==============================================================================
# Manage User Equivalency between all nodes of a cluster
# ==============================================================================

- name: Display pre installation of setting up Oracle Database Software requirements for RHEL 8 and later
  debug:
    msg:
      - 'This playbook is for setting setting up Oracle Database Software requirement {{ansible_date_time.iso8601}}:'

- name: Preparation tasks for hosting Oracle database
  block:
    - import_tasks: Step0_pre-check.yml
    - import_tasks: Step1_facts_to_file.yml
    - import_tasks: Step2_SUDO.yml
    - import_tasks: Step3_oracle_kernelparams.yml
    - import_tasks: Step4_oracle_packages.yml
    - import_tasks: Step5_oracle_users_shell_limit.yml
    - import_tasks: Step6_oracle_host_fileupdate.yml
    - import_tasks: Step7_create_required_dirs.yml
    - import_tasks: Step8_mailx.yml
    # - import_tasks: oracle_bash_profile.yml


#Run the pre as root user
  become: true
  become_exe: "sudo su - "
  become_method: su